language: python

matrix:
  fast_finish: true
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.7-dev
      dist: xenial
      sudo: true
    - python: nightly
      dist: xenial
      sudo: true
  allow_failures:
    - python: nightly
      dist: xenial
      sudo: true
    - python: 3.7-dev
      dist: xenial
      sudo: true

install:
  - pip install pipenv
  - pipenv install --deploy --dev --ignore-pipfile

script:
  - if [[ $TRAVIS_PYTHON_VERSION = "3.7" ]];
    then
      pipenv run slack/tests/test.sh;
    else
      pipenv run pytest test --verbose --cov;
    fi

after_success:
  - coveralls

deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    user: Ovv
    password:
      secure: lldoHkBPyFjcMEWpOMzaXeNdNl1JUgodXfrm9TPT4DYNcQCDU01f6xm8uShBT47mz+tbrUnx2rFhZmTmZAqZDODo7pmkukSrhBRpbLroEp6045MmT4P4aJjoGJooksGouqOsJjqE8yGwyinCVsv0ZNi1RZDxxuUw3Ye+HtDllMNv4XUeEBxOY5LtKpGW/+MF0QZiDggvR2bcLlMJz2EJvtIzhdRtl7fy2eAdrsQoyXhqt7Zuu0y/sc4YTiRt1adLFFFOIDL6mtL76D2eHBQm5oHJM5TtZi0gs633567fyEZ6Gm9fxSo0Ba9L7sen6ApgJLx2yba1+7ititXg7/U7+DvgmFT3Tk294cBRGF/3rhzt60p1xYO1b6tyFK5GTPghidAJZb/OQoMb9L6iZhCmMCukvdW0/241yiLdSQfMbeCzO8diwpwsJiv7k8pWtGTtl2+PtuH26zyZZeuQpu3BlctF5r/hdaiuggoN87RzlOLwqbIRfHZfMGA24LJNbtyRcu3mvaZwFFrRq5NWYqwU2VHQB/plBvB4c+FRyKRIcbiN/G+31WEK3cuMPaKfXM0opJwVpLNA320IHgVxZu0b78Exr2Qs48cBYiEl/BtHYPRYDGscSI5LYZ5cPrGcrhp7Z6jBFTHenq+IW/O21qtxv1h9R9VXyatIGHSW0U/dLOA=
    on:
      repo: pyslackers/slack-sansio
      branch: master
      python: '3.7'
      tags: true
